In [ ]:
import cv2

image = cv2.imread(r"img/img.jpg", cv2.IMREAD_COLOR)
if image is None:
    raise Exception("영상파일 읽기 오류")

x_axis = cv2.flip(image,0)
y_axis = cv2.flip(image,1)
xy_axis = cv2.flip(image,-1)
rep_image = cv2.repeat(image,1,2)
trans_image = cv2.transpose(image)

titles = ['image','x_axis', 'y_axis', 'xy_axis', 'rep_image', 'trans_image']
for title in titles:
    cv2.imshow(title, eval(title))
cv2.waitKey(0)

In [1]:
import numpy as np
import cv2

ch0 = np.zeros((2,4), np.uint8)+10
ch1 = np.ones((2,4), np.uint8)*20
ch2 = np.full((2,4), 30, np.uint8)

list_bgr = [ch0, ch1, ch2]
merge_bgr = cv2.merge(list_bgr)
split_bgr = cv2.split(merge_bgr)

print(f"split_bgr 행렬 형태 : {np.array(split_bgr).shape}")
print(f"merge_bgr 행렬 형태 : {merge_bgr.shape}")
print(f"[ch0] = {ch0}")
print(f"[ch1] = {ch1}")
print(f"[ch2] = {ch2}")
print(f"[merge_bgr] = {merge_bgr}")

print(f"[split_bgr[0]] = {split_bgr[0]}")
print(f"[split_bgr[1]] = {split_bgr[1]}")
print(f"[split_bgr[2]] = {split_bgr[2]}")



split_bgr 행렬 형태 : (3, 2, 4)
merge_bgr 행렬 형태 : (2, 4, 3)
[ch0] = [[10 10 10 10]
 [10 10 10 10]]
[ch1] = [[20 20 20 20]
 [20 20 20 20]]
[ch2] = [[30 30 30 30]
 [30 30 30 30]]
[merge_bgr] = [[[10 20 30]
  [10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]
  [10 20 30]]]
[split_bgr[0]] = [[10 10 10 10]
 [10 10 10 10]]
[split_bgr[1]] = [[20 20 20 20]
 [20 20 20 20]]
[split_bgr[2]] = [[30 30 30 30]
 [30 30 30 30]]


In [3]:
import numpy as np, cv2

m1 = np.full((3,6), 10, np.uint8)
m2 = np.full((3,6), 50, np.uint8)
m_mask = np.zeros(m1.shape, np.uint8)
m_mask[:,3:] = 1

m_add1 = cv2.add(m1,m2)
m_add2 = cv2.add(m1,m2, mask=m_mask)

m_div1 = cv2.divide(m1,m2)
m1 = m1.astype(np.float32)
m2 = np.float32(m2)
m_div2 = cv2.divide(m1,m2)

titles = ['m1','m2', 'm_mask', 'm_add1', 'm_add2', 'm_div1', 'm_div2']
for title in titles:
    print(f"[{title}] = {eval(title)}")


[m1] = [[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]]
[m2] = [[50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]]
[m_mask] = [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
[m_add1] = [[60 60 60 60 60 60]
 [60 60 60 60 60 60]
 [60 60 60 60 60 60]]
[m_add2] = [[ 0  0  0 60 60 60]
 [ 0  0  0 60 60 60]
 [ 0  0  0 60 60 60]]
[m_div1] = [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[m_div2] = [[0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2]]
